version: '3.8'

services:
  zookeeper:
    image: zookeeper:3.7.0
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "flights:1:1,airports:1:1,airlines:1:1,zones:1:1"
    depends_on:
      - zookeeper

  fetch-flight-data:
    build:
      context: .
      dockerfile: Dockerfile.fetch_flight_data
    volumes:
      - ./data:/app/data
    depends_on:
      - kafka

  spark-streaming:
    build:
      context: .
      dockerfile: Dockerfile.spark_streaming
    volumes:
      - ./data:/app/data
    depends_on:
      - kafka

networks:
  default:
    name: flight_radar_network

