version: '3.3'

services:
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    healthcheck:
      test: ["CMD", "echo", "ruok", "|", "nc", "localhost", "2181"]
      interval: 10s
      timeout: 5s
      retries: 5

  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

  fetch_flight_data:
    build:
      context: .
      dockerfile: Dockerfile.fetch_flight_data
    depends_on:
      - kafka

  spark_streaming:
    build:
      context: .
      dockerfile: Dockerfile.spark_streaming
    volumes:
      - flight_data:/data
    depends_on:
      - kafka

  spark_consume:
    build:
      context: .
      dockerfile: Dockerfile.spark_consume
    volumes:
      - flight_data:/data
    depends_on:
      - kafka

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8050:8050"
    volumes:
      - flight_data:/data
    depends_on:
      - spark_consume

volumes:
  flight_data:
