FROM jupyter/pyspark-notebook:latest

WORKDIR /app

RUN mkdir -p /app/data && chmod -R 777 /app/data

COPY spark_streaming.py /app/

CMD ["spark-submit", "--master", "local[2]", "--packages", "org.apache.spark:spark-sql-kafka-0-10_2.12:3.1.1", "/app/spark_streaming.py"]

