version: '3.8'

services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  fetch_flight_data:
    build:
      context: .
      dockerfile: Dockerfile.fetch_flight_data
    depends_on:
      - kafka

  spark_streaming:
    build:
      context: .
      dockerfile: Dockerfile.spark_streaming
    volumes:
      - flight_data:/data
    depends_on:
      - kafka

  spark_consume:
    build:
      context: .
      dockerfile: Dockerfile.spark_consume
    volumes:
      - flight_data:/data
    depends_on:
      - kafka

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "8050:8050"
    volumes:
      - flight_data:/data
    depends_on:
      - spark_consume

volumes:
  flight_data:
